### ISSUE TITLE
virtualenv has old version of python without `datetime` module

### ISSUE THREAD

**Issue by ryanjdillon** [warik/pybrary#3]
It appears the virtualenv included doesn't have datetime, which causes `run.py` to error when run.
http://askubuntu.com/a/542673/109484

**Comment by warik** [comment]
As You may noticed this is quite old project and it was just a test task for my present job. Actually none python project should include virtualenv in repository, just requirements for pip instead. So, You can just ignore this problem.

**Comment by ryanjdillon** [comment]
Cool. Thanks. I was just toying with this to see if it did something. New to contributing, just thought I'd mention it.

**Comment by warik** [comment]
Appreciate Your efforts, but this particular project is not worth contributing)
Sorry for inconvenience.
