### ISSUE TITLE
tmp/pybrary.log not created automatically

### ISSUE THREAD

**Issue by ryanjdillon** [warik/pybrary#4]
error on `db_create.py` run with missing `tmp/pybrary.log`. In `.gitignore`. Maybe I'm doing something stupid... got it to run fine when added manually.

**Comment by warik** [comment]
Yeap, You are right logging init is waiting for file already be creating. Actually its done also incorrect, like almost everything here.
If You wish to fix it - You are welcome, but for me its easier just to delete this old stuff.

**Comment by ryanjdillon** [comment]
No worries. I'll leave this alone now :) Thanks.
